export const HOME_SCREEN = 'HOME_SCREEN';
export const SIGN_UP_SCREEN = 'SIGN_UP_SCREEN';
export const SIGN_IN_SCREEN = 'SIGN_IN_SCREEN';
export const SIGN_HOME_SCREEN = 'SIGN_HOME_SCREEN';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
